#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const project_root = path.resolve(__dirname, '..');

const file = path.join(project_root, 'src', 'rename.room.ts');
console.log(`📝 Generate the rename file: ${file}`);
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export * from 'react-native-chat-room';
`;
fs.writeFileSync(file, content, 'utf-8');
