import type { GiftListModel, ReportItemModel } from './rename.room';

export const gUserNickName1: string[] = [
  'Ethan',
  'Emma',
  'Noah',
  'Olivia',
  'Liam',
  'Ava',
  'Mason',
  'Isabella',
  'Lucas',
  'Sophia',
  'Jackson',
  'Mia',
  'Aiden',
  'Charlotte',
  'Caden',
  'Amelia',
  'Logan',
  'Harper',
  'Grayson',
  'Evelyn',
  'Caleb',
  'Abigail',
  'Jack',
  'Emily',
  'Benjamin',
  'Elizabeth',
  'William',
  'Avery',
  'Michael',
  'Sofia',
  'Alexander',
  'Ella',
  'James',
  'Scarlett',
  'Gabriel',
  'Victoria',
  'Daniel',
  'Madison',
  'Henry',
  'Lily',
  'Matthew',
  'Grace',
  'Joseph',
  'Chloe',
  'Samuel',
  'Hannah',
  'David',
  'Zoey',
  'Levi',
  'Penelope',
  'John',
  'Riley',
  'Andrew',
  'Lillian',
  'Luke',
  'Layla',
  'Owen',
  'Nora',
  'Dylan',
  'Stella',
  'Isaac',
  'Aubrey',
  'Nathan',
  'Maya',
  'Isaac',
  'Lucy',
  'Nicholas',
  'Audrey',
  'Sebastian',
  'Ellie',
  'Julian',
  'Zoe',
  'Carter',
  'Savannah',
  'Caleb',
  'Brooklyn',
  'Cameron',
  'Peyton',
  'Anthony',
  'Claire',
  'Hunter',
  'Anna',
  'Jayden',
  'Natalie',
  'Max',
  'Leah',
  'Eli',
  'Violet',
  'Samuel',
  'Eleanor',
  'Connor',
  'Audrey',
  'Jeremiah',
  'Skylar',
  'Dylan',
  'Naomi',
  'Wyatt',
  'Caroline',
  'Christian',
  'Savannah',
  'Aaron',
  'Alice',
  'Brayden',
  'Genesis',
  'Adrian',
  'Sadie',
  'Jonathan',
  'Julia',
  'Gabriel',
  'Ariana',
  'Colton',
  'Katherine',
  'Isaiah',
  'Paisley',
  'Thomas',
  'Annabelle',
  'Charles',
  'Bella',
  'Josiah',
  'Gabriella',
  'Zachary',
  'Alexis',
  'Jordan',
  'Savannah',
  'Eli',
  'Lucy',
  'Cole',
  'Audrey',
  'Xavier',
  'Alyssa',
  'Landon',
  'Claire',
  'Dominic',
  'Makayla',
  'Carter',
  'Ellie',
  'Angel',
  'Lily',
  'Henry',
  'Kylie',
  'Christopher',
  'Zoe',
  'Adrian',
  'Mila',
  'Leo',
  'Bella',
  'Lincoln',
  'Nora',
  'Jordan',
  'Lydia',
];
export const gUserNickName2: string[] = [
  '左冷禅',
  '朱聪',
  '拜月',
  '周伯通',
  '钟阿四',
  '郑长老',
  '张五侠',
  '张三丰',
  '莫大',
  '张翠山',
  '岳不群',
  '段王爷',
  '袁冠南',
  '袁承志',
  '岳灵珊',
  '余观主',
  '殷天正',
  '尹克西',
  '仪琳',
  '耶律楚材',
  '杨铁心',
  '杨过',
  '杨成协',
  '玄慈大师',
  '虚竹',
  '许仕枫',
  '三少爷',
  '谢逊',
  '逍遥子',
  '小龙女',
  '向问天',
  '张君宝',
  '香香公主',
  '穆人王',
  '夏雪宜',
  '夏冰',
  '无崖子',
  '殷梨亭',
  '文泰来',
  '韦小宝',
  '柯镇恶',
  '王处一',
  '铁心兰',
  '田归农',
  '田伯光',
  '宋青书',
  '双儿',
  '神雕',
  '少庄主',
  '无双',
  '破天',
  '扫地僧',
  '蓉儿',
  '任盈盈',
  '任我行',
  '裘千仞',
  '丘处机',
  '欧阳克',
  '欧阳峰',
  '孙剑',
  '一灯',
  '潇湘子',
  '木婉清',
  '慕容复',
  '慕容博',
  '穆念慈',
  '苗人凤',
  '卓不凡',
  '李秋水',
  '孟铮',
  '孟英霆',
  '孟星魂',
  '孟天明',
  '王语嫣',
  '孟清泉',
  '萧十一郎',
  '梦郎',
  '梦姑',
  '杨开泰',
  '逍遥王',
  '沈浪',
  '梅超风',
  '陈近南',
  '陆无双',
  '鹿清笃',
  '陆乘风',
  '龙儿',
  '龙岛主',
  '柳无眉',
  '柳绘心',
  '令狐冲',
  '林平之',
  '梁子翁',
  '练霓裳',
  '李逍遥',
  '慕容龙城',
  '李萍',
  '老毒物',
  '蓝凤凰',
  '昨夜东风',
  '金轮法王',
  '霍都',
  '黄药师',
  '黄头陀',
  '黄裳',
  '黄衫女子',
  '黄蓉',
  '黄梅',
  '黄老邪',
  '画眉',
  '胡青牛',
  '李莫愁',
  '红袖',
  '洪七公',
  '洪凌波',
  '郭破虏',
  '郭靖',
  '郭芙',
  '归辛树',
  '格老子',
  '葛光佩',
  '天山童姥',
  '风清扬',
  '风良',
  '风波恶',
  '范遥',
  '杨逍',
  '铁木真',
  '阿紫',
  '阿朱',
  '阿柯',
  '阿碧',
  '段正淳',
  '段誉',
  '段延庆',
  '小鱼儿',
  '独孤求败',
  '独孤剑',
  '东方不败',
  '狄云',
  '刀白凤',
  '江枫',
  '程英',
  '程瑶迦',
  '周芷若',
  '傅红雪',
  '白展堂',
  '郭芙蓉',
  '陈家洛',
  '花无缺',
];
export const gUserAvatars: string[] = [
  'fc14ab00-79f7-11ee-93f4-618a64affe88',
  '7345d230-79f8-11ee-a0d1-5f74d88fa308',
  '7d239bc0-79f8-11ee-92b9-770b4e48f8fc',
  '8e208410-79f8-11ee-b8e3-232a619cf52c',
  '99296020-79f8-11ee-8475-c7a7b59db79f',
  'a27bd9a0-79f8-11ee-8f83-551faec94303',
  'ae308610-79f8-11ee-a6c9-5379b9a705a1',
  'b837f7b0-79f8-11ee-b817-23850e48ca47',
  'c0d52af0-79f8-11ee-a6ed-6fc3a8bc6581',
  'c8354a50-79f8-11ee-97b9-0d7ccd9e7127',
  'd2b176c0-79f8-11ee-a291-ed6692473990',
  'de41f960-79f8-11ee-83cd-db9df9bad9bf',
  'e7517670-79f8-11ee-a783-c1d7a432abb7',
  'ef5724a0-79f8-11ee-8290-eb9f9e9c2195',
  'f78da6d0-79f8-11ee-b3b8-3b446ebd1fbb',
  'ffb9efd0-79f8-11ee-9356-ef4cfe1f2af8',
  '07d98ea0-79f9-11ee-8047-d35f49238254',
  '0fa12260-79f9-11ee-890f-67aacef20d88',
  '16bc4980-79f9-11ee-b272-3568dd301252',
  '208dde10-79f9-11ee-b9ea-5bff48db7458',
  '298c9240-79f9-11ee-b8b6-f16f0b5f700a',
];

export const gAvatarUrlBasic =
  'https://a1.easemob.com/easemob/chatroom-uikit/chatfiles/';

export const gRegisterUserUrl =
  'https://a1.easemob.com/internal/appserver/liverooms/user/login';

export const gCreateRoomUrl =
  'https://a1.easemob.com/internal/appserver/liverooms/';

export const gGetRoomListUrl =
  'https://a1.easemob.com/internal/appserver/liverooms';

export const gSendBroadcastUrl =
  'https://a1.easemob.com/internal/appserver/liverooms/broadcast';

export const gRemoveRoomUrl =
  'https://a1.easemob.com/internal/appserver/liverooms/';

export const gGifts: GiftListModel[] = [
  {
    giftId: '2665752a-e273-427c-ac5a-4b2a9c82b255',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift1.png',
    giftName: '爱心',
    giftPrice: 1,
  },
  {
    giftId: 'ff3bbb9e-ef18-430f-aa61-5bddf75eb722',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift2.png',
    giftName: '玫瑰',
    giftPrice: 2,
  },
  {
    giftId: '94f296fa-86d9-4552-84db-025b05ed9f8d',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift3.png',
    giftName: '超级环',
    giftPrice: 5,
  },
  {
    giftId: 'd4cd0526-d8db-4e00-8fc0-d5228907a517',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift4.png',
    giftName: '超级A',
    giftPrice: 10,
  },
  {
    giftId: 'c1997f02-d927-46f5-adda-e6af6714bd75',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift5.png',
    giftName: '星星',
    giftPrice: 20,
  },
  {
    giftId: '0c62b402-376f-4fbb-b584-769a8249189e',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift6.png',
    giftName: '棒棒糖',
    giftPrice: 30,
  },
  {
    giftId: 'ce3f8bc3-74d7-43be-a040-c397d5c49f6d',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift7.png',
    giftName: '钻石',
    giftPrice: 50,
  },
  {
    giftId: '948b1a3b-b2c6-41fc-99b7-a5b9457cd159',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift8.png',
    giftName: '皇冠',
    giftPrice: 100,
  },
  {
    giftId: 'f1e12397-feb7-4c01-b834-f11faf321dbf',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift9.png',
    giftName: '麦克风',
    giftPrice: 500,
  },
  {
    giftId: 'e915438c-7fbd-4e03-840f-0036ec97c824',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift10.png',
    giftEffect:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pag/ballon.pag',
    giftName: '气球',
    giftPrice: 666,
    effectMD5: '141761700268c0290852af8f6a501c10',
  },
  {
    giftId: '0c832b52-8f2e-4202-958b-9410db2d9438',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift11.png',
    giftEffect:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pag/planet.pag',
    giftName: '星球',
    giftPrice: 888,
    effectMD5: '41f3eeff249be268004d82a1d1eaf481',
  },
  {
    giftId: 'beada6a3-eae6-450e-869c-743d02fa95e7',
    giftIcon:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pictures/gift/AUIKitGift12.png',
    giftEffect:
      'https://fullapp.oss-cn-beijing.aliyuncs.com/uikit/pag/rocket.pag',
    giftName: '火箭',
    giftPrice: 1000,
    effectMD5: 'de5094b30eebeadf8b8f5d8357a19578',
  },
];
export const gGifts2 = gGifts.slice(0, gGifts.length - 1);

export const gReportData = [
  {
    id: '1',
    tag: 'tag1',
    title: 'Unwelcome commercial content',
    checked: false,
  },
  {
    id: '2',
    tag: 'tag2',
    title: 'Pornographic or explicit content',
    checked: false,
  },
  {
    id: '3',
    tag: 'tag3',
    title: 'Child abuse',
    checked: false,
  },
  {
    id: '4',
    tag: 'tag4',
    title: 'Hate speech or graphic violence',
    checked: false,
  },
  {
    id: '5',
    tag: 'tag5',
    title: 'Promote terrorism',
    checked: false,
  },
  {
    id: '6',
    tag: 'tag6',
    title: 'Harassment or bullying',
    checked: false,
  },
  {
    id: '7',
    tag: 'tag7',
    title: 'Suicide or self harm',
    checked: false,
  },
  {
    id: '8',
    tag: 'tag8',
    title: 'False information',
    checked: false,
  },
  {
    id: '9',
    tag: 'tag9',
    title: 'Others',
    checked: false,
  },
] as ReportItemModel[];
