#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const { current_dir, current_package, color_log } = require('./utils');

const out_file = path.join(current_dir, 'src', 'env.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} env file: ${out_file}`
);
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export const test = false;
export const isDevMode = true;
export const appKey = '';
export const appId = '';
export const accountType = ''; // agora | easemob | shengwang // only with callkit
export const agoraAppId = '';
export const fcmSenderId = '';
export const demoType = 1; // 1. ui-dev 2. dev 3. prod
export const reactStrictMode = false;
export const appServerDomain = ''; // for app demo
export const restServerDomain = ''; // for chat sdk
export const useAppServerDomain = true;
export const account = [{ id: '', token: '' }];
export const useSandbox = false;
export const enableDNSConfig = true;
export const imPort = 0;
export const imServer = '';
`;
if (fs.existsSync(out_file) === false) {
  fs.writeFileSync(out_file, content, 'utf-8');
}
