#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const { current_dir, current_package, color_log } = require('./utils');

const out_callkit_file = path.join(current_dir, 'src', 'rename.callkit.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} rename file: ${out_callkit_file}`
);
const callkit_content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export * from 'react-native-chat-callkit';
`;
fs.writeFileSync(out_callkit_file, callkit_content, 'utf-8');

const out_uikit_file = path.join(current_dir, 'src', 'rename.uikit.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} rename file: ${out_uikit_file}`
);

const uikit_content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export * from 'react-native-chat-uikit';
`;
fs.writeFileSync(out_uikit_file, uikit_content, 'utf-8');
