tasks.register('moveCodegenDirs') {
    doLast {
        def libRoot = new File("${rootDir}/../../../packages/react-native-chat-room")
        def sourceDir = new File(libRoot, "android/generated")
        def targetDir = new File(libRoot, "android/build/generated/source/codegen")

        println "sourceDir: ${sourceDir}"
        println "targetDir: ${targetDir}"

        if (targetDir.exists()) {
            println "remove targetDir: ${targetDir}"
            targetDir.deleteDir()
        }

        targetDir.getParentFile().mkdirs()

        if (sourceDir.exists()) {
            println "move: ${sourceDir} -> ${targetDir}"
            ant.move(file: sourceDir, tofile: targetDir)
        } else {
            println "sourceDir not exists: ${sourceDir}"
        }
    }
}

tasks.register('invokeLibraryCodegen', Exec) {
    workingDir "$rootDir/../../../packages/react-native-chat-room"
    def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')
    if (isWindows) {
        commandLine 'cmd', '/c', 'yarn bob build --target codegen'
    } else {
        commandLine 'sh', '-c', 'yarn bob build --target codegen'
    }
}

def isNewArchitectureEnabled() {
    return rootProject.hasProperty("newArchEnabled") && rootProject.getProperty("newArchEnabled") == "true"
}

println("isNewArchitectureEnabled: ${isNewArchitectureEnabled()}")

if (isNewArchitectureEnabled()) {
    if (tasks.findByPath('invokeLibraryCodegen') != null) {
        moveCodegenDirs.mustRunAfter invokeLibraryCodegen
        preBuild.dependsOn invokeLibraryCodegen, moveCodegenDirs
    }
}
