#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const { current_dir, current_package, color_log } = require('./utils');

const out_file = path.join(current_dir, 'src', 'config.local.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} config file: ${out_file}`
);
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export const language = 'zh-Hans'; // 'en' or 'zh-Hans'
export const release_area = 'china'; // 'china' or 'global'
`;
if (fs.existsSync(out_file) === false) {
  fs.writeFileSync(out_file, content, 'utf-8');
}
