#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const { current_dir, current_package, color_log } = require('./utils');

const out_file_callkit = path.join(current_dir, 'src', 'rename.callkit.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} rename file: ${out_file_callkit}`
);
const content_callkit = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export * from 'react-native-chat-callkit';
`;
fs.writeFileSync(out_file_callkit, content_callkit, 'utf-8');
