/**
 * Custom Expo config plugin to inject Android permissions into AndroidManifest.xml.
 *
 * Permissions added:
 *   - CAMERA              : required for taking photos/videos
 *   - RECORD_AUDIO        : required for recording voice messages
 *   - READ_MEDIA_IMAGES   : required for reading photos on Android 13+ (API 33+)
 *   - READ_MEDIA_VIDEO    : required for reading videos on Android 13+ (API 33+)
 *
 * Note: INTERNET, READ_EXTERNAL_STORAGE (maxSdk=32), WRITE_EXTERNAL_STORAGE (maxSdk=32)
 * are already present in the base AndroidManifest.xml generated by Expo prebuild.
 */
const { withAndroidManifest } = require('@expo/config-plugins');

/**
 * @param {import('@expo/config-plugins').ExpoConfig} config
 * @returns {import('@expo/config-plugins').ExpoConfig}
 */
module.exports = function withAndroidPermissions(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;

    if (!manifest['uses-permission']) {
      manifest['uses-permission'] = [];
    }

    const permissionsToAdd = [
      // Camera access — all Android versions
      'android.permission.CAMERA',
      // Audio recording — all Android versions
      'android.permission.RECORD_AUDIO',
      // Scoped media access for Android 13+ (API 33+)
      'android.permission.READ_MEDIA_IMAGES',
      'android.permission.READ_MEDIA_VIDEO',
    ];

    for (const permission of permissionsToAdd) {
      const already = manifest['uses-permission'].some(
        (p) => p.$ && p.$['android:name'] === permission
      );
      if (!already) {
        manifest['uses-permission'].push({
          $: { 'android:name': permission },
        });
      }
    }

    return config;
  });
};
