#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const { current_dir, current_package, color_log } = require('./utils');

const out_file = path.join(current_dir, 'src', 'env.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} env file: ${out_file}`
);
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export const isDevMode = true;
export const appKey = '';
export const accountType = 'easemob'; // agora or easemob
export const agoraAppId = '';
export const gAvatarUrlBasic = '';
export const gRegisterUserUrl = '';
export const gCreateRoomUrl = '';
export const gGetRoomListUrl = '';
export const reactStrictMode = false;
export const account = [{ id: '', token: '' }];
`;
if (fs.existsSync(out_file) === false) {
  fs.writeFileSync(out_file, content, 'utf-8');
}
