#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const { current_dir, current_package, color_log } = require('./utils');

const out_room_file = path.join(current_dir, 'src', 'rename.room.ts');
color_log.success(
  `📝 Generate the ${current_package.name}@${current_package.version} rename file: ${out_room_file}`
);
const room_content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export * from 'react-native-chat-room';
`;
fs.writeFileSync(out_room_file, room_content, 'utf-8');
