#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const project_root = path.resolve(__dirname, '..');

const pak = JSON.parse(
  fs.readFileSync(path.join(project_root, 'package.json'), 'utf8')
);
const file = path.join(project_root, 'src', 'env.ts');
console.log(`📝 Generate the ${pak.name}@${pak.version} env file: ${file}`);
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export const test = true;
export const useSendBox = false;
export const isDevMode = true;
export const appKey = '';
export const accountType = ''; // agora or easemob
export const agoraAppId = '';
export const demoType = 1; // 1. ui-dev 2. dev 3. prod
export const account = [{ id: '', token: '' }];
`;
if (fs.existsSync(file) === false) {
  fs.writeFileSync(file, content, 'utf-8');
}
