def createMoveCodegenDirsTask(String wd, String libName) {
    return tasks.register("moveCodegenDirs_${libName}", Task) {
        doLast {
            def libRoot = new File(wd)
            def sourceDir = new File(libRoot, "android/generated")
            def targetDir = new File(libRoot, "android/build/generated/source/codegen")

            println "workingDir: ${wd}"
            println "sourceDir: ${sourceDir}"
            println "targetDir: ${targetDir}"

            if (targetDir.exists()) {
                println "remove targetDir: ${targetDir}"
                targetDir.deleteDir()
            }

            targetDir.getParentFile().mkdirs()

            if (sourceDir.exists()) {
                println "move: ${sourceDir} -> ${targetDir}"
                ant.move(file: sourceDir, tofile: targetDir)
            } else {
                println "sourceDir not exists: ${sourceDir}"
            }
        }
    }
}

def createInvokeLibraryCodegenTask(String wd, String libName) {
    return tasks.register("invokeLibraryCodegen_${libName}", Exec) {
        workingDir wd
        println "workingDir: ${wd}"
        def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')
        if (isWindows) {
            commandLine 'cmd', '/c', 'yarn bob build --target codegen'
        } else {
            commandLine 'sh', '-c', 'yarn bob build --target codegen'
        }
    }
}

def isNewArchitectureEnabled() {
    return rootProject.hasProperty("newArchEnabled") && rootProject.getProperty("newArchEnabled") == "true"
}

println("isNewArchitectureEnabled: ${isNewArchitectureEnabled()}")

if (isNewArchitectureEnabled()) {
    def roomName = "react-native-chat-room"
    def roomPath = "${rootDir}/../../../packages/${roomName}"
    def roomTaskName = "room"
    println "roomPath: ${roomPath}"
    def roomInvokeTask = createInvokeLibraryCodegenTask(roomPath, roomTaskName)
    def roomMoveTask = createMoveCodegenDirsTask(roomPath, roomTaskName)
    roomMoveTask.configure { it.mustRunAfter(roomInvokeTask.get()) }
    preBuild.dependsOn(roomInvokeTask.get(), roomMoveTask.get())
}
