// 产生这个问题的堆栈
// example/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake: 该文件的 多了 add_subdirectory，并且 路径是错误的
// node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/GenerateAutolinkingNewArchitecturesFileTask.kt: 该文件 和 生成 Android-autolinking.cmake 有关
// node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: 该文件 和 生成 autolinking.json 有关
// node_modules/@react-native/gradle-plugin/settings-plugin/src/main/kotlin/com/facebook/react/ReactSettingsExtension.kt: 该文件 和 生成 autolinking.json 有关
// todo: 后续有时间再研究下 2025-03-26
//
// 可以确定的是，如果 使用 `npx @react-native-community/cli@latest init --version 0.76 simple_demo` 创建项目， 并且集成 expo，则不会产生这个问题
// 如果使用 `npx create-react-native-library@latest --reactNativeVersion=0.76.7   react-native-chat-uikit` 创建项目，并且集成 expo ，则会产生这个问题



tasks.register('moveCodegenDirs') {
    doLast {
        def libRoot = new File("${rootDir}/../../../packages/react-native-chat-uikit")
        def sourceDir = new File(libRoot, "android/generated")
        def targetDir = new File(libRoot, "android/build/generated/source/codegen")

        println "sourceDir: ${sourceDir}"
        println "targetDir: ${targetDir}"

        if (targetDir.exists()) {
            println "remove targetDir: ${targetDir}"
            targetDir.deleteDir()
        }

        targetDir.getParentFile().mkdirs()

        if (sourceDir.exists()) {
            println "move: ${sourceDir} -> ${targetDir}"
            ant.move(file: sourceDir, tofile: targetDir)
        } else {
            println "sourceDir not exists: ${sourceDir}"
        }
    }
}

tasks.register('invokeLibraryCodegen', Exec) {
    workingDir "$rootDir/../../../packages/react-native-chat-uikit"
    def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')
    if (isWindows) {
        commandLine 'cmd', '/c', 'yarn bob build --target codegen'
    } else {
        commandLine 'sh', '-c', 'yarn bob build --target codegen'
    }
}

def isNewArchitectureEnabled() {
    return rootProject.hasProperty("newArchEnabled") && rootProject.getProperty("newArchEnabled") == "true"
}

println("isNewArchitectureEnabled: ${isNewArchitectureEnabled()}")

if (isNewArchitectureEnabled()) {
    if (tasks.findByPath('invokeLibraryCodegen') != null) {
        moveCodegenDirs.mustRunAfter invokeLibraryCodegen
        preBuild.dependsOn invokeLibraryCodegen, moveCodegenDirs
    }
}
